### ISSUE TITLE
Resource not found: agribot_launch

### ISSUE THREAD

**Issue by fri-K** [PRBonn/visual-crop-row-navigation#3]
Hi,
i'm using Ubuntu 18.04 to build this project but I can't find agribot_launch
Steps to reproduce:
create catkin workspace:` mkdir -p catkin_ws/src`
clone this repo to catkin_ws/src
command to build: `catkin_make visual-crop-row-navigation`
command to source environment: `source devel/setup.sh`
run roslaunch: `roslaunch visual_crop_row_navigation visualservoing.launch`

But it fails with:
```
catkin_ws$ roslaunch visual_crop_row_navigation visualservoing.launch
... logging to /home/user/.ros/log/2da74dfa-9d8b-11ea-92d9-80000b3e8feb/roslaunch-user-19017.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: agribot_launch
ROS path [0]=/usr/share/ros
ROS path [1]=/home/user/catkin_ws/src
ROS path [2]=/usr/share
The traceback for the exception was written to the log file
```

In readme there is 

> A complete Gazebo simulation package is provided in [agribot_robot]() repository including simulated row-crop fields and robot for testing the navigation framework.

but  i can't find agribot_robot repository anywhere. Could you please tell me where I can find it?

**Comment by alirezaahmadi** [comment]
Hi the simulation package is added to the readme file of the project, also the agribot_launch package is only used to run the usbCam package which I will update and put it inside  the current launch folder ...
good luck
