### ISSUE TITLE
Missing reference to agribot_robot

### ISSUE THREAD

**Issue by caiofis** [PRBonn/visual-crop-row-navigation#4]
Hi,
I am looking for the gazebo simulation files that you talk about in the README but cannot find it, seems like you forgot the add the link. Where can I find it?

**Comment by alirezaahmadi** [comment]
Will try to add it in coming days.

**Comment by alirezaahmadi** [comment]
Hi, 
I updated the readme file and added the robot simulation package ... you can find the link to Agribot simulation inside the readme
