### ISSUE TITLE
Visual servoing within overall ROS2 nav strategy

### ISSUE THREAD

**Issue by samuk** [PRBonn/visual-crop-row-navigation#6]
Your work is being discussed here: https://discourse.ros.org/t/navigation-for-precision-farming-in-open-fields/15138/13

With a discussion of how it could fit within an overall ROS2 navigation. Do you have any contributions you could add there?

Do you know roughly when your Python version will be available?

Thanks

Sam

**Comment by alirezaahmadi** [comment]
you can find a python version (it is early release so code needs to be cleaned up a little bit) here 
https://github.com/Agricultural-Robotics-Bonn/visual-multi-crop-row-navigation
